[general]
live_config_reload = true

[window]
decorations = "none"
startup_mode = "Maximized"
# Other window settings can go here, e.g.
# opacity = 0.90

[font]
normal = { family = "Monaspace Neon NF", style = "SemiBold" }
size = 12.5

[terminal]
shell = "/bin/zsh"

[colors.primary]
background = '#000000'
foreground = '#eaeaea'

[colors.normal]
black   = '#000000'
red     = '#d54e53'
green   = '#b9ca4a'
yellow  = '#e6c547'
blue    = '#7aa6da'
magenta = '#c397d8'
cyan    = '#70c0ba'
white   = '#424242'

[colors.bright]
black   = '#666666'
red     = '#ff3334'
green   = '#9ec400'
yellow  = '#e7c547'
blue    = '#7aa6da'
magenta = '#b77ee0'
cyan    = '#54ced6'
white   = '#2a2a2a'

[window.dimensions]
columns = 100
lines = 40

